### ISSUE TITLE
Chutes not deploying on booster stage

### ISSUE THREAD

**Issue by westlakem** [ChrisViral/RealChute#108] opened 2023-03-21 17:35 UTC
I'm using FMRS to do a landing of my first stage, and the chutes I have on the booster won't open.

They're staged, listed as "safe", and under the pre-deployment altitude, and they just won't open.

![image](https://user-images.githubusercontent.com/4505074/226695074-5b7f8a6e-bd51-43fe-a8a6-4ede37605c70.png)

**Comment by ChrisViral** [comment] 2024-05-25 22:04
Cannot determine the issue without logs. Due to it's age at this point, I'll be closing this one, but if you can reproduce this, feel free to open a new one and I'll gladly take logs along to see what the problem is.

**Closed by ChrisViral** 2024-05-25 22:04 UTC
